### PR TITLE
Dashboard models with dummy data

### PR DESCRIPTION
**Pull request by thanhgly**
I created fictitious data that matched the actual data structure and fed it into the models. As a result, when sending GET requests to dashboard endpoints, the response should contain counterfeit data that matches the expected format.

### CODE REVIEW

**Comment by gbmyt** [comment]
Are these dummy data objects meant to mirror our current database structure? If so, I’ve noticed some discrepancies— listing below:

_(CREATE TABLE query for the following should either be modified to add these columns to existing tables, or dummy data objects can be merged with the understanding that these columns do not currently exist/cannot be interacted with in the database)_

Overview looks good to go 

My Quizzes: Type, Plays, and Date columns do not exist in Quizzes table 

History: Quiz Name + Plays columns not in current history table 

Favorites: Quiz Name, Total Plays and Total Likes columns not in current favorites table

**Comment by thanhgly** [comment]
@gbmyt Thank you for bringing this to my attention. I intend to use aggregation techniques in the query to structure the data. Concerning My Quizzes, I presume that the created quizzes will have a created_at column, whereas plays will represent the total number of times other users have taken the quiz, which I will create by combining aggregation methods with the history table. As there are only two kinds of quizzes, I may choose to remove the type header. The same principle applies to the History and Favorites categories.

**Comment by gbmyt** [comment]
@thanhgly -- since these objects don't really impact the current flow I think this is fine to merge, just wanted to make sure you're aware of the current table structure. I'm attaching a couple screenshots to the current schema file, any missing columns will need to be added before you can interact with them on the front-end

[Schema Screencap 1](https://bit.ly/3LK5NGW)
[Schema Screencap 2](https://bit.ly/3LJ6gsQ)

**Review by gbmyt — APPROVED** [review]
Gtg

**Pull request merged**
