### PR TITLE
Delete like unlike functionalities 

### PR DESCRIPTION
**Pull request by thanhgly**
Changes:
- Completed delete, like, and unlike quizzes.
- Fixed some query mistakes.

The core features of the User Dashboard are completed.

### CODE REVIEW

**Review by gbmyt — COMMENTED** [review]
Reviewed and noticed a couple things: 

- Confirmed ability to favorite a quiz from the History tab. Once "liked" the quiz appears in my Dashboard Favorites tab.

- Confirmed ability to delete a quiz, however-- it gets deleted from my account and dash, but it is then added to the database under 'guest' for some reason (not sure if this originates from delete functionality or somewhere else in the application, will try to locate the bug)

- I'm not sure if the click-a-header to filter functionality is meant to work on the History tab. If not, this note is good to disregard otherwise I noticed nothing happens when a header is clicked under that 'History' tab.

Everything else looks good to merge

**Comment by thanhgly** [comment]
@gbmyt 
I made a hotfix to the filter function.
For the delete strategy, I followed @tigerkh3 suggestions to change the ownership to admin instead of deleting the quiz.

Help me review it again. Thank you.

**Comment by gbmyt** [comment]
Pulled down again and the filter functionality still doesn't work on the History tab, but on all the other tabs it works great-- I'm seeing an error about multiple children with the same key, not sure if that's related. 

Like/Delete functionality works and is good to merge

**Review by gbmyt — APPROVED** [review]
Pulled again and the filter functionality seems to be working now. Good to merge ✅

**Pull request merged**
