### PR TITLE
Patched Nav Bar Redirects to Home Screen on Page Refresh

### PR DESCRIPTION
**Pull request by gbmyt**
Added some logic to the useEffect hook in the Nav bar component. Now, if a user refreshes the page while in the middle of taking a Quiz, they won't be redirected to the Home Screen

### CODE REVIEW

**Review by thanhgly — CHANGES_REQUESTED** [review]
I pulled the PR. Seems like my switch logic and useNavigate is indeed a bad idea. I have re-implemented it with React Router Link, and the problem is fixed. I have tried clicking on the nav bar and changing the url, and it seems to work well. Should I push this up to your branch or should I make a separate branch for this?

**Comment by gbmyt** [comment]
Thanks for looking into that @thanhgly, I think you're good to push changes to this branch/PR and I'll pull them down to take a peek

**Review by thanhgly — APPROVED** [review]
Changes made to your PR. I think it's safe to merge.

**Comment by gbmyt** [comment]
Looks good, thanks for the adjustment! Removed test links from App.jsx / merging

**Pull request merged**
